export default {
    status:0,
    books:[
        {
            name:"Javascript 高级程序设计-第三版-中文版",
            bookUrl:"https://pan.baidu.com/s/12HMZvRauF4NgEvWEe65qfA",
            key:"gdgq"
        },
        {
            name:"JavaScript权威指南(第6版)-中文版",
            bookUrl:"https://pan.baidu.com/s/1uKgt58ioyYBRReTA33OsCQ",
            key:"hj2o"
        },
        {
            name:"JavaScript语言精粹-中文版",
            bookUrl:"https://pan.baidu.com/s/1X1B87eTNk93KwDvggKbz8Q",
            key:" vgzt"
        },
        {
            name:"JavaScript设计模式",
            bookUrl:"https://pan.baidu.com/s/1HC5A3Mf2uvMIgShw9edjBA",
            key:"xw62"
        },
        {
            name:"你不知道的JavaScript上中下",
            bookUrl:"https://pan.baidu.com/s/1fn23A39n_50RnC7Vyvj5yw",
            key:"ku1u"
        },
        {
            name:"HTML5揭秘",
            bookUrl:"https://pan.baidu.com/s/1S-jxbbR6BG0cnGzkiPQH7g",
            key:"z7lw"
        },
        {
            name:"CSS权威指南（第3版）",
            bookUrl:"https://pan.baidu.com/s/1NPRoiitWlQjrJMErucHsow",
            key:"6clz"
        },
        {
            name:"CSS揭秘-中文版",
            bookUrl:"https://pan.baidu.com/s/1gierGGVLRqWbRdRkSkPVoQ",
            key:"2xgj"
        },
        {
            name:"精通CSS：高级 Web 标准解决方案（第2版）",
            bookUrl:"https://pan.baidu.com/s/1XHw_VodKf4LM7WmCfdyL6w",
            key:"gwuz"
        },
        {
            name:"HTTP权威指南",
            bookUrl:"https://pan.baidu.com/s/1tW5A0S4g5fq3jYDZ0dIlDg",
            key:"8prz"
        },
        {
            name:"图解HTTP",
            bookUrl:"https://pan.baidu.com/s/1uWtxB8wOAQp4VqG2_9lBfA",
            key:"54hx"
        },
        {
            name:"白帽子讲Web安全",
            bookUrl:"https://pan.baidu.com/s/1mkYnvElNMHgVXgrfB2axJQ",
            key:"skdv"
        },
        {
            name:"web前端黑客技术揭秘",
            bookUrl:"https://pan.baidu.com/s/1ha2D7OroSBLG5InO92d3CQ",
            key:"su8k"
        },
        {
            name:"学习JavaScript数据结构与算法（第2版）",
            bookUrl:"ttps://pan.baidu.com/s/1qoRJBQQFAQjPCn61TOzngg",
            key:"2iss"
        }
    ]
}

